from dataclasses import dataclass
from typing import Optional


@dataclass
class PlayData:
    id: Optional[int] = None
    idx: str = None
    title: str = None
    difficulty: str = None
    track: Optional[str] = None
    music_type: Optional[str] = None
    new_achievement: Optional[bool] = None
    achievement: Optional[str] = None
    rank: Optional[str] = None
    new_dx_score: Optional[bool] = None
    dx_score: Optional[str] = None
    dx_stars: Optional[int] = None
    combo_status: Optional[str] = None
    sync_status: Optional[str] = None
    place: Optional[str] = None
    played_at: Optional[str] = None
    fast: Optional[int] = None
    late: Optional[int] = None
    tap_critical: Optional[int] = None
    tap_perfect: Optional[int] = None
    tap_great: Optional[int] = None
    tap_good: Optional[int] = None
    tap_miss: Optional[int] = None
    hold_critical: Optional[int] = None
    hold_perfect: Optional[int] = None
    hold_great: Optional[int] = None
    hold_good: Optional[int] = None
    hold_miss: Optional[int] = None
    slide_critical: Optional[int] = None
    slide_perfect: Optional[int] = None
    slide_great: Optional[int] = None
    slide_good: Optional[int] = None
    slide_miss: Optional[int] = None
    touch_critical: Optional[int] = None
    touch_perfect: Optional[int] = None
    touch_great: Optional[int] = None
    touch_good: Optional[int] = None
    touch_miss: Optional[int] = None
    break_critical: Optional[int] = None
    break_perfect: Optional[int] = None
    break_great: Optional[int] = None
    break_good: Optional[int] = None
    break_miss: Optional[int] = None
    combo: Optional[int] = None
    max_combo: Optional[int] = None
    sync: Optional[int] = None
    max_sync: Optional[int] = None
    detailed: Optional[bool] = None
    play_data_version: Optional[int] = None
